function out1 = curlH_D(z0,r0,in3,in4)
%CURLH_D
%    OUT1 = CURLH_D(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 08:42:45

yfDv1d2 = in3(2,:);
yfDv1d3 = in3(3,:);
yfDv1d4 = in3(4,:);
yfDv1d5 = in3(5,:);
yfDv1d6 = in3(6,:);
yfDv3d1 = in3(15,:);
yfDv3d2 = in3(16,:);
yfDv3d3 = in3(17,:);
yfDv3d4 = in3(18,:);
yfDv3d5 = in3(19,:);
yfDv3d6 = in3(20,:);
yfDv4d2 = in3(23,:);
yfDv4d3 = in3(24,:);
yfDv4d4 = in3(25,:);
yfDv4d5 = in3(26,:);
yfDv4d6 = in3(27,:);
t2 = yfDv3d2.*yfDv4d3;
t3 = yfDv3d3.*yfDv4d2;
t4 = yfDv3d2.*yfDv4d5;
t5 = yfDv3d3.*yfDv4d4;
t6 = yfDv3d4.*yfDv4d3;
t7 = yfDv3d5.*yfDv4d2;
t8 = yfDv3d2.*yfDv4d6;
t9 = yfDv3d6.*yfDv4d2;
t10 = yfDv3d3.*yfDv4d6;
t11 = yfDv3d6.*yfDv4d3;
t12 = 1.0./yfDv3d1;
t13 = -t3;
t14 = -t6;
t15 = -t7;
t16 = -t8;
t17 = -t10;
t18 = t2+t13;
t23 = t5+t9+t14+t16;
t24 = t4+t11+t15+t17;
t19 = 1.0./t18;
t20 = t19.^2;
t21 = t19.*yfDv3d6;
t22 = t19.*yfDv4d6;
out1 = t12.^2.*(t19.*yfDv1d2.*yfDv4d3-t19.*yfDv1d3.*yfDv4d2)+t12.*(yfDv1d3.*(t19.*yfDv3d3.*(t19.*yfDv3d4+t20.*t23.*yfDv3d2)-t19.*yfDv3d2.*(t21-t20.*t24.*yfDv3d2))+yfDv1d2.*(t19.*yfDv3d2.*(t19.*yfDv3d5-t20.*t24.*yfDv3d3)-t19.*yfDv3d3.*(t21+t20.*t23.*yfDv3d3))-t20.*yfDv1d4.*yfDv3d3.^2-t20.*yfDv1d5.*yfDv3d2.^2+t20.*yfDv1d6.*yfDv3d2.*yfDv3d3.*2.0)+t12.*(yfDv1d3.*(t19.*yfDv4d3.*(t19.*yfDv4d4+t20.*t23.*yfDv4d2)-t19.*yfDv4d2.*(t22-t20.*t24.*yfDv4d2))+yfDv1d2.*(t19.*yfDv4d2.*(t19.*yfDv4d5-t20.*t24.*yfDv4d3)-t19.*yfDv4d3.*(t22+t20.*t23.*yfDv4d3))-t20.*yfDv1d4.*yfDv4d3.^2-t20.*yfDv1d5.*yfDv4d2.^2+t20.*yfDv1d6.*yfDv4d2.*yfDv4d3.*2.0);
