function out1 = curlH_A(z1,r1,in3,in4)
%CURLH_A
%    OUT1 = CURLH_A(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2021 10:12:30

yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
yf1v4d4 = in3(25,:);
yf1v4d5 = in3(26,:);
yf1v4d6 = in3(27,:);
yf1v5d1 = in3(29,:);
yf1v5d3 = in3(31,:);
yf1v5d5 = in3(33,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v6d5 = in3(40,:);
yf1v11d1 = in3(71,:);
t2 = 1.0./yf1v5d3;
t3 = yf1v6d1-yf1v11d1;
t4 = 1.0./t3;
t5 = 1.0./yf1v5d3.^2;
t6 = yf1v6d3.^2;
t7 = 1.0./t3.^2;
t8 = 1.0./yf1v5d1;
out1 = 1.0./yf1v5d1.^2.*(t2.*yf1v4d3-r1.*t2.*t4.*yf1v4d2.*yf1v6d3)-t8.*(t2.*(t2.*yf1v4d5-r1.*t2.*t4.*yf1v4d6.*yf1v6d3)+yf1v4d2.*(t2.*(r1.*t2.*t6.*t7-r1.*t2.*t4.*yf1v6d5+r1.*t4.*t5.*yf1v5d5.*yf1v6d3)+r1.*t5.*t6.*t7)-yf1v4d3.*1.0./yf1v5d3.^3.*yf1v5d5-r1.*t2.*t4.*yf1v6d3.*(t2.*yf1v4d6-r1.*t2.*t4.*yf1v4d4.*yf1v6d3))-t7.*t8.*yf1v4d4;
