function [FAAlinea9b,dFAAlinea9b] = equationFAAlinea9bstream(z1,r1,in3,in4)
%EQUATIONFAALINEA9BSTREAM
%    [FAALINEA9B,DFAALINEA9B] = EQUATIONFAALINEA9BSTREAM(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 10:26:39

yf1v3d1 = in3(15,:);
FAAlinea9b = yf1v3d1;
if nargout > 1
    dFAAlinea9b = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
