function [FEElinea2,dFEElinea2] = equationFEElinea2(z1,r1,in3,in4)
%EQUATIONFEELINEA2
%    [FEELINEA2,DFEELINEA2] = EQUATIONFEELINEA2(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2021 10:18:53

yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d3 = in3(17,:);
t2 = 1.0./yf1v2d3;
FEElinea2 = [yf1v1d1,yf1v2d1,t2.*yf1v3d3];
if nargout > 1
    dFEElinea2 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2.^2.*yf1v3d3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
