function [FAAlinea3,dFAAlinea3] = equationFAAlinea3stream(z1,r1,in3,in4)
%EQUATIONFAALINEA3STREAM
%    [FAALINEA3,DFAALINEA3] = EQUATIONFAALINEA3STREAM(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 10:26:38

yf1v3d1 = in3(15,:);
FAAlinea3 = yf1v3d1;
if nargout > 1
    dFAAlinea3 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
