function [FCClinea6_c,dFCClinea6_c] = equationFCClinea6_c(z1,r1,in3,in4,phid_c)
%EQUATIONFCCLINEA6_C
%    [FCCLINEA6_C,DFCCLINEA6_C] = EQUATIONFCCLINEA6_C(Z1,R1,IN3,IN4,PHID_C)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:27

pa_5 = in4(5,:);
pa_7 = in4(7,:);
pa_15 = in4(15,:);
pa_16 = in4(16,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d2 = in3(9,:);
yf1v3d1 = in3(15,:);
t2 = yf1v2d1.^2;
t3 = 1.0./pi;
t4 = -pa_5;
t5 = -pa_7;
t6 = pa_5+t5;
t7 = r1.*t6;
t8 = pa_16+t4+t7;
t9 = t8.^2;
t10 = t2+t9;
FCClinea6_c = [yf1v3d1+(pa_15.*t3.*t8.*1.0./t10.^(3.0./2.0))./4.0,yf1v2d2,-phid_c+yf1v1d1];
if nargout > 1
    dFCClinea6_c = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,pa_15.*t3.*t8.*1.0./t10.^(5.0./2.0).*yf1v2d1.*(-3.0./4.0),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
