function [FBBlinea4,dFBBlinea4] = equationFBBlinea4(z1,r1,in3,in4)
%EQUATIONFBBLINEA4
%    [FBBLINEA4,DFBBLINEA4] = EQUATIONFBBLINEA4(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2021 11:45:34

pa_5 = in4(5,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d1 = in3(15,:);
yf1v3d3 = in3(17,:);
yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
t2 = r1-1.0;
t3 = -yf1v3d1;
t4 = 1.0./yf1v2d3;
t5 = t4.^2;
t6 = pa_5+t3;
t7 = 1.0./t6;
FBBlinea4 = [yf1v1d1,yf1v2d1,yf1v3d3,t4.*yf1v4d3+t2.*t4.*t7.*yf1v3d3.*yf1v4d2];
if nargout > 1
    dFBBlinea4 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t5.*yf1v4d3-t2.*t5.*t7.*yf1v3d3.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t4.*t7.^2.*yf1v3d3.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,t2.*t4.*t7.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t4.*t7.*yf1v3d3,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,28]);
end
