function [FEElinea1_c,dFEElinea1_c] = equationFEElinea1_c(z1,r1,in3,in4,phid_c)
%EQUATIONFEELINEA1_C
%    [FEELINEA1_C,DFEELINEA1_C] = EQUATIONFEELINEA1_C(Z1,R1,IN3,IN4,PHID_C)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2021 10:18:52

pa_15 = in4(15,:);
pa_16 = in4(16,:);
pa_30 = in4(30,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d2 = in3(9,:);
yf1v3d1 = in3(15,:);
t2 = pa_30.*r1;
t3 = yf1v2d1.^2;
t4 = 1.0./pi;
t5 = -pa_30;
t6 = pa_16+t2+t5;
t7 = t6.^2;
t8 = t3+t7;
FEElinea1_c = [yf1v3d1+(pa_15.*t4.*t6.*1.0./t8.^(3.0./2.0))./4.0,yf1v2d2,-phid_c+yf1v1d1];
if nargout > 1
    dFEElinea1_c = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,pa_15.*t4.*t6.*1.0./t8.^(5.0./2.0).*yf1v2d1.*(-3.0./4.0),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
