function [FAAlinea11,dFAAlinea11] = equationFAAlinea11stream(z1,r1,in3,in4)
%EQUATIONFAALINEA11STREAM
%    [FAALINEA11,DFAALINEA11] = EQUATIONFAALINEA11STREAM(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 10:26:38

yf1v3d2 = in3(16,:);
yf1v3d3 = in3(17,:);
yf1v5d1 = in3(29,:);
yf1v5d3 = in3(31,:);
yf1v5d7 = in3(35,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v6d7 = in3(42,:);
yf1v11d1 = in3(71,:);
t2 = -yf1v11d1;
t3 = 1.0./yf1v5d1;
t5 = 1.0./yf1v5d3;
t4 = t3.^2;
t6 = t5.^2;
t7 = t5.*yf1v3d3;
t8 = t2+yf1v6d1;
t9 = 1.0./t8;
t10 = t9.^2;
t11 = t3.*t9.*yf1v3d2;
t14 = r1.*t5.*t9.*yf1v3d2.*yf1v6d3;
t12 = t3.*t10.*yf1v3d2.*yf1v6d3;
t15 = -t14;
t13 = r1.*t12;
t16 = t7+t15;
t17 = t3.*t16;
FAAlinea11 = yf1v6d3.*(t11+yf1v5d7)+yf1v5d3.*(t17-yf1v6d7);
if nargout > 1
    dFAAlinea11 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3.*t9.*yf1v6d3-r1.*t3.*t9.*yf1v6d3,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t4.*t16.*yf1v5d3-t4.*t9.*yf1v3d2.*yf1v6d3,0.0,t17-yf1v6d7-t3.*yf1v5d3.*(t6.*yf1v3d3-r1.*t6.*t9.*yf1v3d2.*yf1v6d3),0.0,0.0,0.0,yf1v6d3,-t12+t13,0.0,t11+yf1v5d7-r1.*t11,0.0,0.0,0.0,-yf1v5d3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t12-t13,0.0,0.0,0.0,0.0,0.0,0.0];
end
