function [FEDDlinea19,dFEDDlinea19] = equationFEDDlinea19(z0,r0,in3,in4)
%EQUATIONFEDDLINEA19
%    [FEDDLINEA19,DFEDDLINEA19] = EQUATIONFEDDLINEA19(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Feb-2021 08:56:12

yfDv1d1 = in3(1,:);
yfDv2d1 = in3(8,:);
FEDDlinea19 = [-yfDv1d1,0.0,-yfDv2d1];
if nargout > 1
    dFEDDlinea19 = reshape([-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,28]);
end
