function [FVertexEAD,dFVertexEAD] = equationVertexEAD(z1,r1,in3,in4)
%EQUATIONVERTEXEAD
%    [FVERTEXEAD,DFVERTEXEAD] = EQUATIONVERTEXEAD(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2021 10:18:53

pa_6 = in4(6,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v3d1 = in3(15,:);
FVertexEAD = [yf1v1d1,-pa_6+yf1v2d1,yf1v3d1];
if nargout > 1
    dFVertexEAD = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
