function [FVertexAD,dFVertexAD] = equationFVertexADstream(z1,r1,in3,in4)
%EQUATIONFVERTEXADSTREAM
%    [FVERTEXAD,DFVERTEXAD] = EQUATIONFVERTEXADSTREAM(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 10:26:36

yf1v3d1 = in3(15,:);
FVertexAD = yf1v3d1;
if nargout > 1
    dFVertexAD = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
