function [FCClinea12,dFCClinea12] = equationFCClinea12(z1,r1,in3,in4)
%EQUATIONFCCLINEA12
%    [FCCLINEA12,DFCCLINEA12] = EQUATIONFCCLINEA12(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:27

pa_5 = in4(5,:);
pa_7 = in4(7,:);
yf1v1d2 = in3(2,:);
yf1v2d1 = in3(8,:);
yf1v3d2 = in3(16,:);
t2 = -pa_7;
t3 = pa_5+t2;
t4 = 1.0./t3;
FCClinea12 = [t4.*yf1v1d2,-yf1v2d1,t4.*yf1v3d2];
if nargout > 1
    dFCClinea12 = reshape([0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
