function [FVertexDBCC,dFVertexDBCC] = equationFVertexDBCC(z1,r1,in3,in4)
%EQUATIONFVERTEXDBCC
%    [FVERTEXDBCC,DFVERTEXDBCC] = EQUATIONFVERTEXDBCC(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 15:31:15

pa_5 = in4(5,:);
pa_7 = in4(7,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v3d1 = in3(15,:);
FVertexDBCC = [yf1v1d1,yf1v3d1,yf1v2d1,pa_5-r1.*(pa_5-pa_7),0.0];
if nargout > 1
    dFVertexDBCC = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,21]);
end
