function [FVertexDABB,dFVertexDABB] = equationFVertexDABB(z1,r1,in3,in4)
%EQUATIONFVERTEXDABB
%    [FVERTEXDABB,DFVERTEXDABB] = EQUATIONFVERTEXDABB(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 15:29:06

pa_5 = in4(5,:);
yf1v1d2 = in3(2,:);
yf1v1d3 = in3(3,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d1 = in3(15,:);
yf1v3d3 = in3(17,:);
yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
t2 = r1-1.0;
t3 = -yf1v3d1;
t4 = 1.0./yf1v2d3;
t5 = t4.^2;
t6 = pa_5+t3;
t7 = 1.0./t6;
t8 = t7.^2;
t9 = t2.*t4.*t7.*yf1v3d3;
FVertexDABB = [t4.*yf1v1d3+t9.*yf1v1d2,t4.*yf1v4d3+t9.*yf1v4d2,yf1v2d1,yf1v3d1+r1.*t6,0.0];
if nargout > 1
    dFVertexDABB = reshape([0.0,0.0,0.0,0.0,0.0,t9,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t5.*yf1v1d3-t2.*t5.*t7.*yf1v1d2.*yf1v3d3,-t5.*yf1v4d3-t2.*t5.*t7.*yf1v3d3.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t4.*t8.*yf1v1d2.*yf1v3d3,t2.*t4.*t8.*yf1v3d3.*yf1v4d2,0.0,-t2,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t4.*t7.*yf1v1d2,t2.*t4.*t7.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t9,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,28]);
end
