function [FCClinea5,dFCClinea5] = equationFCClinea5(z1,r1,in3,in4)
%EQUATIONFCCLINEA5
%    [FCCLINEA5,DFCCLINEA5] = EQUATIONFCCLINEA5(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:28

yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d3 = in3(17,:);
t2 = 1.0./yf1v2d3;
FCClinea5 = [yf1v1d1,yf1v2d1,t2.*yf1v3d3];
if nargout > 1
    dFCClinea5 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2.^2.*yf1v3d3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
