function [FVertexCDB,dFVertexCDB] = equationFVertexCDB(z1,r1,in3,in4)
%EQUATIONFVERTEXCDB
%    [FVERTEXCDB,DFVERTEXCDB] = EQUATIONFVERTEXCDB(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:26

pa_6 = in4(6,:);
yf1v1d3 = in3(3,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d3 = in3(17,:);
t2 = 1.0./yf1v2d3;
FVertexCDB = [t2.*yf1v1d3,-pa_6+yf1v2d1,t2.*yf1v3d3];
if nargout > 1
    t3 = t2.^2;
    dFVertexCDB = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-t3.*yf1v1d3,0.0,-t3.*yf1v3d3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
