function [FAAlinea9r,dFAAlinea9r] = equationFAAlinea9rstream(z1,r1,in3,in4)
%EQUATIONFAALINEA9RSTREAM
%    [FAALINEA9R,DFAALINEA9R] = EQUATIONFAALINEA9RSTREAM(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 10:26:39

yf1v3d1 = in3(15,:);
FAAlinea9r = yf1v3d1;
if nargout > 1
    dFAAlinea9r = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
