function [FCClinea6_m,dFCClinea6_m] = equationFCClinea6_m(z1,r1,in3,in4)
%EQUATIONFCCLINEA6_M
%    [FCCLINEA6_M,DFCCLINEA6_M] = EQUATIONFCCLINEA6_M(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:28

pa_5 = in4(5,:);
pa_7 = in4(7,:);
pa_15 = in4(15,:);
pa_16 = in4(16,:);
pa_17 = in4(17,:);
pa_18 = in4(18,:);
yf1v1d1 = in3(1,:);
yf1v2d1 = in3(8,:);
yf1v2d2 = in3(9,:);
yf1v3d1 = in3(15,:);
t2 = yf1v2d1.^2;
t3 = 1.0./pi;
t4 = -pa_5;
t5 = -pa_7;
t6 = pa_5+t5;
t7 = r1.*t6;
t8 = pa_16+t4+t7;
t9 = pa_18+t4+t7;
t10 = t8.^2;
t11 = t9.^2;
t12 = t2+t10;
t13 = t2+t11;
FCClinea6_m = [yf1v3d1+(pa_15.*t3.*t8.*1.0./t12.^(3.0./2.0))./4.0+(pa_17.*t3.*t9.*1.0./t13.^(3.0./2.0))./4.0,yf1v2d2,yf1v1d1];
if nargout > 1
    dFCClinea6_m = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,pa_15.*t3.*t8.*1.0./t12.^(5.0./2.0).*yf1v2d1.*(-3.0./4.0)-pa_17.*t3.*t9.*1.0./t13.^(5.0./2.0).*yf1v2d1.*(3.0./4.0),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,21]);
end
