function [FCBlinea12,dFCBlinea12] = equationFCBlinea12(z1,r1,in3,in4)
%EQUATIONFCBLINEA12
%    [FCBLINEA12,DFCBLINEA12] = EQUATIONFCBLINEA12(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2021 11:45:36

pa_5 = in4(5,:);
yf1v1d2 = in3(2,:);
yf1v2d1 = in3(8,:);
yf1v3d1 = in3(15,:);
yf1v4d2 = in3(23,:);
t2 = -yf1v3d1;
t3 = pa_5+t2;
t4 = 1.0./t3;
FCBlinea12 = [t4.*yf1v1d2,yf1v2d1,t4.*yf1v4d2];
if nargout > 1
    t5 = t4.^2;
    dFCBlinea12 = reshape([0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5.*yf1v1d2,0.0,t5.*yf1v4d2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,28]);
end
