function [FBClinea12,dFBClinea12] = equationFBClinea12(z1,r1,in3,in4)
%EQUATIONFBCLINEA12
%    [FBCLINEA12,DFBCLINEA12] = EQUATIONFBCLINEA12(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:28

yf1v1d1 = in3(1,:);
yf1v3d1 = in3(15,:);
FBClinea12 = [-yf1v1d1,0.0,0.0,-yf1v3d1];
if nargout > 1
    dFBClinea12 = reshape([-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,21]);
end
