function [Hra,Hza] = MagneticfieldEEa(z1,r1,in3,in4)
%MAGNETICFIELDEEA
%    [HRA,HZA] = MAGNETICFIELDEEA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2021 10:18:52

pa_30 = in4(30,:);
yf1v1d3 = in3(3,:);
yf1v1d5 = in3(5,:);
yf1v2d3 = in3(10,:);
yf1v2d5 = in3(12,:);
yf1v3d2 = in3(16,:);
Hra = 0.0;
if nargout > 1
    Hza = yf1v3d2./pa_30+yf1v1d5.*1.0./yf1v2d3.^2-yf1v1d3.*1.0./yf1v2d3.^3.*yf1v2d5;
end
