function [Mr,Mz] = MagneticvectorAA(z1,r1,in3,in4)
%MAGNETICVECTORAA
%    [MR,MZ] = MAGNETICVECTORAA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2021 10:13:10

yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
yf1v5d1 = in3(29,:);
yf1v5d3 = in3(31,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v7d1 = in3(43,:);
yf1v9d2 = in3(58,:);
yf1v9d3 = in3(59,:);
yf1v11d1 = in3(71,:);
t2 = 1.0./yf1v5d3;
t3 = yf1v6d1-yf1v11d1;
t4 = 1.0./t3;
t5 = 1.0./yf1v5d1;
Mr = -yf1v7d1.*(t2.*yf1v9d3+t4.*t5.*yf1v4d2-r1.*t2.*t4.*yf1v6d3.*yf1v9d2);
if nargout > 1
    Mz = yf1v7d1.*(t5.*(t2.*yf1v4d3-r1.*t2.*t4.*yf1v4d2.*yf1v6d3)-t4.*yf1v9d2);
end
