function [Hra,Hza] = MagneticfieldBBa(z1,r1,in3,in4)
%MAGNETICFIELDBBA
%    [HRA,HZA] = MAGNETICFIELDBBA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2021 11:45:29

pa_5 = in4(5,:);
yf1v1d2 = in3(2,:);
yf1v1d3 = in3(3,:);
yf1v1d4 = in3(4,:);
yf1v1d5 = in3(5,:);
yf1v1d6 = in3(6,:);
yf1v2d3 = in3(10,:);
yf1v2d5 = in3(12,:);
yf1v3d1 = in3(15,:);
yf1v3d3 = in3(17,:);
yf1v3d5 = in3(19,:);
yf1v4d2 = in3(23,:);
Hra = 0.0;
if nargout > 1
    t2 = yf1v3d3.^2;
    t3 = r1-1.0;
    t4 = -yf1v3d1;
    t5 = 1.0./yf1v2d3;
    t6 = t5.^2;
    t7 = pa_5+t4;
    t8 = 1.0./t7;
    t9 = t8.^2;
    Hza = t5.*(t5.*yf1v1d5+t3.*t5.*t8.*yf1v1d6.*yf1v3d3)-t8.*yf1v4d2+yf1v1d2.*(t5.*(t2.*t3.*t5.*t9+t3.*t5.*t8.*yf1v3d5-t3.*t6.*t8.*yf1v2d5.*yf1v3d3)+t2.*t3.*t6.*t9)-t5.^3.*yf1v1d3.*yf1v2d5+t3.*t5.*t8.*yf1v3d3.*(t5.*yf1v1d6+t3.*t5.*t8.*yf1v1d4.*yf1v3d3);
end
