function [Hra,Hza] = MagneticfieldDDa(z0,r0,in3,in4)
%MAGNETICFIELDDDA
%    [HRA,HZA] = MAGNETICFIELDDDA(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 08:42:46

yfDv1d2 = in3(2,:);
yfDv1d3 = in3(3,:);
yfDv1d4 = in3(4,:);
yfDv1d5 = in3(5,:);
yfDv1d6 = in3(6,:);
yfDv2d2 = in3(9,:);
yfDv2d3 = in3(10,:);
yfDv3d2 = in3(16,:);
yfDv3d3 = in3(17,:);
yfDv3d4 = in3(18,:);
yfDv3d5 = in3(19,:);
yfDv3d6 = in3(20,:);
yfDv4d2 = in3(23,:);
yfDv4d3 = in3(24,:);
yfDv4d4 = in3(25,:);
yfDv4d5 = in3(26,:);
yfDv4d6 = in3(27,:);
Hra = 0.0;
if nargout > 1
    t2 = yfDv3d2.*yfDv4d3;
    t3 = yfDv3d3.*yfDv4d2;
    t4 = yfDv3d2.*yfDv4d5;
    t5 = yfDv3d3.*yfDv4d4;
    t6 = yfDv3d4.*yfDv4d3;
    t7 = yfDv3d5.*yfDv4d2;
    t8 = yfDv3d2.*yfDv4d6;
    t9 = yfDv3d6.*yfDv4d2;
    t10 = yfDv3d3.*yfDv4d6;
    t11 = yfDv3d6.*yfDv4d3;
    t12 = -t3;
    t13 = -t6;
    t14 = -t7;
    t15 = -t8;
    t16 = -t10;
    t17 = t2+t12;
    t21 = t5+t9+t13+t15;
    t22 = t4+t11+t14+t16;
    t18 = 1.0./t17;
    t19 = t18.^2;
    t20 = t18.*yfDv4d6;
    Hza = -yfDv1d3.*(t18.*yfDv4d3.*(t18.*yfDv4d4+t19.*t21.*yfDv4d2)-t18.*yfDv4d2.*(t20-t19.*t22.*yfDv4d2))-yfDv1d2.*(t18.*yfDv4d2.*(t18.*yfDv4d5-t19.*t22.*yfDv4d3)-t18.*yfDv4d3.*(t20+t19.*t21.*yfDv4d3))+t19.*yfDv1d4.*yfDv4d3.^2+t19.*yfDv1d5.*yfDv4d2.^2+t18.*yfDv2d2.*yfDv3d3-t18.*yfDv2d3.*yfDv3d2-t19.*yfDv1d6.*yfDv4d2.*yfDv4d3.*2.0;
end
