function [Hr,Hz] = MagneticfieldDD(z0,r0,in3,in4)
%MAGNETICFIELDDD
%    [HR,HZ] = MAGNETICFIELDDD(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 08:42:45

yfDv1d2 = in3(2,:);
yfDv1d3 = in3(3,:);
yfDv2d2 = in3(9,:);
yfDv2d3 = in3(10,:);
yfDv3d1 = in3(15,:);
yfDv3d2 = in3(16,:);
yfDv3d3 = in3(17,:);
yfDv4d2 = in3(23,:);
yfDv4d3 = in3(24,:);
t2 = yfDv3d2.*yfDv4d3;
t3 = yfDv3d3.*yfDv4d2;
t4 = 1.0./yfDv3d1;
t5 = -t3;
t6 = t2+t5;
t7 = 1.0./t6;
Hr = t4.*(t7.*yfDv1d2.*yfDv3d3-t7.*yfDv1d3.*yfDv3d2)-t7.*yfDv2d2.*yfDv4d3+t7.*yfDv2d3.*yfDv4d2;
if nargout > 1
    Hz = t4.*(t7.*yfDv1d2.*yfDv4d3-t7.*yfDv1d3.*yfDv4d2)+t7.*yfDv2d2.*yfDv3d3-t7.*yfDv2d3.*yfDv3d2;
end
