function [Hr,Hz] = MagneticfieldCC(z1,r1,in3,in4)
%MAGNETICFIELDCC
%    [HR,HZ] = MAGNETICFIELDCC(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 19:04:27

pa_5 = in4(5,:);
pa_7 = in4(7,:);
yf1v1d2 = in3(2,:);
yf1v1d3 = in3(3,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d2 = in3(16,:);
yf1v3d3 = in3(17,:);
t2 = -pa_7;
t3 = 1.0./yf1v2d1;
t4 = 1.0./yf1v2d3;
t5 = pa_5+t2;
t6 = 1.0./t5;
Hr = -t4.*yf1v3d3+t3.*t6.*yf1v1d2;
if nargout > 1
    Hz = t6.*yf1v3d2+t3.*t4.*yf1v1d3;
end
