function [M,Mz1,Hra,Hza] = MagneticfieldAAa(z1,r1,in3,in4)
%MAGNETICFIELDAAA
%    [M,MZ1,HRA,HZA] = MAGNETICFIELDAAA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2021 10:13:09

yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
yf1v4d4 = in3(25,:);
yf1v4d5 = in3(26,:);
yf1v4d6 = in3(27,:);
yf1v5d1 = in3(29,:);
yf1v5d3 = in3(31,:);
yf1v5d5 = in3(33,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v6d5 = in3(40,:);
yf1v7d1 = in3(43,:);
yf1v9d2 = in3(58,:);
yf1v9d3 = in3(59,:);
yf1v11d1 = in3(71,:);
t2 = 1.0./yf1v5d3;
t3 = yf1v6d1-yf1v11d1;
t4 = 1.0./t3;
t6 = 1.0./yf1v5d1;
t8 = t4.*yf1v9d2;
t9 = t2.*yf1v4d3;
t10 = r1.*t2.*t4.*yf1v4d2.*yf1v6d3;
t11 = t9-t10;
t12 = t6.*t11;
t5 = t8-t12;
t14 = t2.*yf1v9d3;
t15 = t4.*t6.*yf1v4d2;
t16 = r1.*t2.*t4.*yf1v6d3.*yf1v9d2;
t7 = t14+t15-t16;
t13 = t5.^2;
t17 = t7.^2;
t18 = t13+t17+2.220446049250313e-16;
t19 = sqrt(t18);
M = t19.*yf1v7d1;
if nargout > 1
    Mz1 = r1.*t3.*t19.*yf1v7d1;
end
if nargout > 2
    Hra = 0.0;
end
if nargout > 3
    t20 = 1.0./yf1v5d3.^2;
    t21 = yf1v6d3.^2;
    t22 = 1.0./t3.^2;
    Hza = -t8+t2.*(t2.*yf1v4d5-r1.*t2.*t4.*yf1v4d6.*yf1v6d3)+yf1v4d2.*(t2.*(r1.*t2.*t21.*t22-r1.*t2.*t4.*yf1v6d5+r1.*t4.*t20.*yf1v5d5.*yf1v6d3)+r1.*t20.*t21.*t22)-yf1v4d3.*1.0./yf1v5d3.^3.*yf1v5d5-r1.*t2.*t4.*yf1v6d3.*(t2.*yf1v4d6-r1.*t2.*t4.*yf1v4d4.*yf1v6d3);
end
