function [Hr,Hz] = MagneticfieldEE(z1,r1,in3,in4)
%MAGNETICFIELDEE
%    [HR,HZ] = MAGNETICFIELDEE(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2021 10:18:52

pa_30 = in4(30,:);
yf1v1d2 = in3(2,:);
yf1v1d3 = in3(3,:);
yf1v2d1 = in3(8,:);
yf1v2d3 = in3(10,:);
yf1v3d2 = in3(16,:);
yf1v3d3 = in3(17,:);
t2 = 1.0./pa_30;
t3 = 1.0./yf1v2d1;
t4 = 1.0./yf1v2d3;
Hr = -t4.*yf1v3d3+t2.*t3.*yf1v1d2;
if nargout > 1
    Hz = t2.*yf1v3d2+t3.*t4.*yf1v1d3;
end
