function [M,Mz1,Hr,Hz] = MagneticfieldAA(z1,r1,in3,in4)
%MAGNETICFIELDAA
%    [M,MZ1,HR,HZ] = MAGNETICFIELDAA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2021 10:13:11

yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
yf1v5d1 = in3(29,:);
yf1v5d3 = in3(31,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v7d1 = in3(43,:);
yf1v9d2 = in3(58,:);
yf1v9d3 = in3(59,:);
yf1v11d1 = in3(71,:);
t2 = 1.0./yf1v5d3;
t3 = yf1v6d1-yf1v11d1;
t4 = 1.0./t3;
t6 = 1.0./yf1v5d1;
t8 = t4.*yf1v9d2;
t9 = t2.*yf1v4d3;
t10 = r1.*t2.*t4.*yf1v4d2.*yf1v6d3;
t11 = t9-t10;
t12 = t6.*t11;
t5 = t8-t12;
t14 = t2.*yf1v9d3;
t15 = t4.*t6.*yf1v4d2;
t16 = r1.*t2.*t4.*yf1v6d3.*yf1v9d2;
t7 = t14+t15-t16;
t13 = t5.^2;
t17 = t7.^2;
t18 = t13+t17+2.220446049250313e-16;
t19 = sqrt(t18);
M = t19.*yf1v7d1;
if nargout > 1
    Mz1 = r1.*t3.*t19.*yf1v7d1;
end
if nargout > 2
    Hr = -t14-t15+t16;
end
if nargout > 3
    Hz = -t8+t12;
end
