function [dphir,dphiz,dphirr,dphizz,dphirz,dpsir,dpsiz,dpsirr,dpsizz,dpsirz] = potentialsAA(z1,r1,in3,in4)
%POTENTIALSAA
%    [DPHIR,DPHIZ,DPHIRR,DPHIZZ,DPHIRZ,DPSIR,DPSIZ,DPSIRR,DPSIZZ,DPSIRZ] = POTENTIALSAA(Z1,R1,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2021 10:12:31

yf1v4d2 = in3(23,:);
yf1v4d3 = in3(24,:);
yf1v4d4 = in3(25,:);
yf1v4d5 = in3(26,:);
yf1v4d6 = in3(27,:);
yf1v5d3 = in3(31,:);
yf1v5d5 = in3(33,:);
yf1v6d1 = in3(36,:);
yf1v6d3 = in3(38,:);
yf1v6d5 = in3(40,:);
yf1v9d2 = in3(58,:);
yf1v9d3 = in3(59,:);
yf1v9d4 = in3(60,:);
yf1v9d5 = in3(61,:);
yf1v9d6 = in3(62,:);
yf1v11d1 = in3(71,:);
t2 = 1.0./yf1v5d3;
t3 = yf1v6d1-yf1v11d1;
t4 = 1.0./t3;
dphir = t2.*yf1v4d3-r1.*t2.*t4.*yf1v4d2.*yf1v6d3;
if nargout > 1
    dphiz = t4.*yf1v4d2;
end
if nargout > 2
    t5 = 1.0./yf1v5d3.^2;
    t6 = yf1v6d3.^2;
    t7 = 1.0./t3.^2;
    t8 = r1.*t2.*t6.*t7;
    t9 = r1.*t4.*t5.*yf1v5d5.*yf1v6d3;
    t10 = t8+t9-r1.*t2.*t4.*yf1v6d5;
    t11 = t2.*t10;
    t12 = r1.*t5.*t6.*t7;
    t13 = t11+t12;
    t14 = 1.0./yf1v5d3.^3;
    dphirr = t2.*(t2.*yf1v4d5-r1.*t2.*t4.*yf1v4d6.*yf1v6d3)+t13.*yf1v4d2-t14.*yf1v4d3.*yf1v5d5-r1.*t2.*t4.*yf1v6d3.*(t2.*yf1v4d6-r1.*t2.*t4.*yf1v4d4.*yf1v6d3);
end
if nargout > 3
    dphizz = t7.*yf1v4d4;
end
if nargout > 4
    dphirz = t2.*t4.*yf1v4d6-t2.*t7.*yf1v4d2.*yf1v6d3-r1.*t2.*t7.*yf1v4d4.*yf1v6d3;
end
if nargout > 5
    dpsir = t2.*yf1v9d3-r1.*t2.*t4.*yf1v6d3.*yf1v9d2;
end
if nargout > 6
    dpsiz = t4.*yf1v9d2;
end
if nargout > 7
    dpsirr = t2.*(t2.*yf1v9d5-r1.*t2.*t4.*yf1v6d3.*yf1v9d6)+t13.*yf1v9d2-t14.*yf1v5d5.*yf1v9d3-r1.*t2.*t4.*yf1v6d3.*(t2.*yf1v9d6-r1.*t2.*t4.*yf1v6d3.*yf1v9d4);
end
if nargout > 8
    dpsizz = t7.*yf1v9d4;
end
if nargout > 9
    dpsirz = t2.*t4.*yf1v9d6-t2.*t7.*yf1v6d3.*yf1v9d2-r1.*t2.*t7.*yf1v6d3.*yf1v9d4;
end
