function [dphidr,dphidz,dphidrr,dphidzz,dphidrz,dpsidr,dpsidz,dpsidrr,dpsidzz,dpsidrz] = potentialsDD(z0,r0,in3,in4)
%POTENTIALSDD
%    [DPHIDR,DPHIDZ,DPHIDRR,DPHIDZZ,DPHIDRZ,DPSIDR,DPSIDZ,DPSIDRR,DPSIDZZ,DPSIDRZ] = POTENTIALSDD(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2021 08:42:51

yfDv1d2 = in3(2,:);
yfDv1d3 = in3(3,:);
yfDv1d4 = in3(4,:);
yfDv1d5 = in3(5,:);
yfDv1d6 = in3(6,:);
yfDv2d2 = in3(9,:);
yfDv2d3 = in3(10,:);
yfDv2d4 = in3(11,:);
yfDv2d5 = in3(12,:);
yfDv2d6 = in3(13,:);
yfDv3d2 = in3(16,:);
yfDv3d3 = in3(17,:);
yfDv3d4 = in3(18,:);
yfDv3d5 = in3(19,:);
yfDv3d6 = in3(20,:);
yfDv4d2 = in3(23,:);
yfDv4d3 = in3(24,:);
yfDv4d4 = in3(25,:);
yfDv4d5 = in3(26,:);
yfDv4d6 = in3(27,:);
t2 = yfDv3d2.*yfDv4d3;
t3 = yfDv3d3.*yfDv4d2;
t4 = yfDv3d2.*yfDv4d5;
t5 = yfDv3d3.*yfDv4d4;
t6 = yfDv3d4.*yfDv4d3;
t7 = yfDv3d5.*yfDv4d2;
t8 = yfDv3d2.*yfDv4d6;
t9 = yfDv3d6.*yfDv4d2;
t10 = yfDv3d3.*yfDv4d6;
t11 = yfDv3d6.*yfDv4d3;
t12 = yfDv3d2.^2;
t13 = yfDv3d3.^2;
t14 = yfDv4d2.^2;
t15 = yfDv4d3.^2;
t16 = -t3;
t17 = -t6;
t18 = -t7;
t19 = -t8;
t20 = -t10;
t21 = t2+t16;
t30 = t5+t9+t17+t19;
t31 = t4+t11+t18+t20;
t22 = 1.0./t21;
dphidr = t22.*yfDv1d2.*yfDv4d3-t22.*yfDv1d3.*yfDv4d2;
if nargout > 1
    dphidz = -t22.*yfDv1d2.*yfDv3d3+t22.*yfDv1d3.*yfDv3d2;
end
if nargout > 2
    t23 = t22.^2;
    t24 = t22.*yfDv3d4;
    t25 = t22.*yfDv3d5;
    t26 = t22.*yfDv3d6;
    t27 = t22.*yfDv4d4;
    t28 = t22.*yfDv4d5;
    t29 = t22.*yfDv4d6;
    t32 = t23.*t30.*yfDv3d2;
    t33 = t23.*t30.*yfDv3d3;
    t34 = t23.*t31.*yfDv3d2;
    t35 = t23.*t31.*yfDv3d3;
    t36 = t23.*t30.*yfDv4d2;
    t37 = t23.*t30.*yfDv4d3;
    t38 = t23.*t31.*yfDv4d2;
    t39 = t23.*t31.*yfDv4d3;
    t40 = -t34;
    t41 = -t35;
    t42 = -t38;
    t43 = -t39;
    t44 = t24+t32;
    t45 = t26+t33;
    t46 = t27+t36;
    t47 = t29+t37;
    t48 = t25+t41;
    t49 = t26+t40;
    t50 = t28+t43;
    t51 = t29+t42;
    t52 = t22.*t44.*yfDv3d3;
    t53 = t22.*t45.*yfDv3d3;
    t54 = t22.*t44.*yfDv4d3;
    t55 = t22.*t45.*yfDv4d3;
    t56 = t22.*t46.*yfDv4d3;
    t57 = t22.*t47.*yfDv4d3;
    t58 = t22.*t48.*yfDv3d2;
    t59 = t22.*t49.*yfDv3d2;
    t60 = t22.*t48.*yfDv4d2;
    t61 = t22.*t49.*yfDv4d2;
    t62 = t22.*t50.*yfDv4d2;
    t63 = t22.*t51.*yfDv4d2;
    t64 = -t58;
    t65 = -t59;
    t66 = -t60;
    t67 = -t61;
    t68 = -t62;
    t69 = -t63;
    t70 = t52+t65;
    t71 = t53+t64;
    t72 = t54+t67;
    t73 = t55+t66;
    t74 = t56+t69;
    t75 = t57+t68;
    dphidrr = -t74.*yfDv1d3+t75.*yfDv1d2+t14.*t23.*yfDv1d5+t15.*t23.*yfDv1d4-t23.*yfDv1d6.*yfDv4d2.*yfDv4d3.*2.0;
end
if nargout > 3
    dphidzz = -t70.*yfDv1d3+t71.*yfDv1d2+t12.*t23.*yfDv1d5+t13.*t23.*yfDv1d4-t23.*yfDv1d6.*yfDv3d2.*yfDv3d3.*2.0;
end
if nargout > 4
    dphidrz = t72.*yfDv1d3-t73.*yfDv1d2-t22.*yfDv3d2.*(t22.*yfDv1d5.*yfDv4d2-t22.*yfDv1d6.*yfDv4d3)-t22.*yfDv3d3.*(t22.*yfDv1d4.*yfDv4d3-t22.*yfDv1d6.*yfDv4d2);
end
if nargout > 5
    dpsidr = t22.*yfDv2d2.*yfDv4d3-t22.*yfDv2d3.*yfDv4d2;
end
if nargout > 6
    dpsidz = -t22.*yfDv2d2.*yfDv3d3+t22.*yfDv2d3.*yfDv3d2;
end
if nargout > 7
    dpsidrr = -t74.*yfDv2d3+t75.*yfDv2d2+t14.*t23.*yfDv2d5+t15.*t23.*yfDv2d4-t23.*yfDv2d6.*yfDv4d2.*yfDv4d3.*2.0;
end
if nargout > 8
    dpsidzz = -t70.*yfDv2d3+t71.*yfDv2d2+t12.*t23.*yfDv2d5+t13.*t23.*yfDv2d4-t23.*yfDv2d6.*yfDv3d2.*yfDv3d3.*2.0;
end
if nargout > 9
    dpsidrz = t72.*yfDv2d3-t73.*yfDv2d2-t22.*yfDv3d2.*(t22.*yfDv2d5.*yfDv4d2-t22.*yfDv2d6.*yfDv4d3)-t22.*yfDv3d3.*(t22.*yfDv2d4.*yfDv4d3-t22.*yfDv2d6.*yfDv4d2);
end
