function [fitresult, gof] = createFit_MsVsRho(rho_data, Ms_data)
%CREATEFIT(RHO_DATA,MS_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: rho_data
%      Y Output: Ms_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Dec-2023 14:29:01


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( rho_data, Ms_data );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 2' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Ms_data vs. rho_data', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'rho_data', 'Interpreter', 'none' );
% ylabel( 'Ms_data', 'Interpreter', 'none' );
% grid on


