function [FDDlinea8,dFDDlinea8] = equationFDDlinea8_mg(z0,r0,in3,in4)
%EQUATIONFDDLINEA8_MG
%    [FDDLINEA8,DFDDLINEA8] = EQUATIONFDDLINEA8_MG(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Apr-2021 11:28:19

pa_1 = in4(1,:);
pa_5 = in4(5,:);
yfDv1d1 = in3(1,:);
yfDv2d1 = in3(8,:);
FDDlinea8 = [-pa_1+yfDv1d1,-pa_5+yfDv2d1];
if nargout > 1
    dFDDlinea8 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,14]);
end
