function [FDD,dFDD] = equationFDD_mg(z0,r0,in3,in4)
%EQUATIONFDD_MG
%    [FDD,DFDD] = EQUATIONFDD_MG(Z0,R0,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Apr-2021 11:28:18

pa_4 = in4(4,:);
yfDv1d1 = in3(1,:);
yfDv1d2 = in3(2,:);
yfDv1d3 = in3(3,:);
yfDv2d2 = in3(9,:);
yfDv2d3 = in3(10,:);
yfDv2d4 = in3(11,:);
yfDv2d5 = in3(12,:);
yfDv2d6 = in3(13,:);
t2 = yfDv1d2.^2;
t3 = yfDv1d3.^2;
t4 = yfDv2d2.^2;
t5 = yfDv2d3.^2;
t6 = yfDv1d2.*yfDv1d3.*2.0;
t7 = yfDv2d2.*yfDv2d3.*2.0;
t8 = t2+t4;
t9 = t3+t5;
FDD = [-pa_4+yfDv1d1,-yfDv2d6.*(t6+t7)+t8.*yfDv2d5+t9.*yfDv2d4];
if nargout > 1
    dFDD = reshape([1.0,0.0,0.0,yfDv1d2.*yfDv2d5.*2.0-yfDv1d3.*yfDv2d6.*2.0,0.0,yfDv1d3.*yfDv2d4.*2.0-yfDv1d2.*yfDv2d6.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,yfDv2d2.*yfDv2d5.*2.0-yfDv2d3.*yfDv2d6.*2.0,0.0,yfDv2d3.*yfDv2d4.*2.0-yfDv2d2.*yfDv2d6.*2.0,0.0,t9,0.0,t8,0.0,-t6-t7,0.0,0.0],[2,14]);
end
