function [dux,duy,duxx,duyy,duxy] = derivativesN6(in1,in2,in3,in4,in5,in6,in7)
%DERIVATIVESN6
%    [DUX,DUY,DUXX,DUYY,DUXY] = DERIVATIVESN6(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Sep-2018 16:31:11

A11 = in7(:,1);
A12 = in7(:,6);
A13 = in7(:,11);
A14 = in7(:,16);
A15 = in7(:,21);
A21 = in7(:,2);
A22 = in7(:,7);
A23 = in7(:,12);
A24 = in7(:,17);
A25 = in7(:,22);
A31 = in7(:,3);
A32 = in7(:,8);
A33 = in7(:,13);
A34 = in7(:,18);
A35 = in7(:,23);
A41 = in7(:,4);
A42 = in7(:,9);
A43 = in7(:,14);
A44 = in7(:,19);
A45 = in7(:,24);
A51 = in7(:,5);
A52 = in7(:,10);
A53 = in7(:,15);
A54 = in7(:,20);
A55 = in7(:,25);
va1 = in1(:,1);
va2 = in1(:,2);
va3 = in1(:,3);
va4 = in1(:,4);
va5 = in1(:,5);
va6 = in1(:,6);
x1r1 = in2(:,1);
x1r2 = in2(:,2);
x1r3 = in2(:,3);
x1r4 = in2(:,4);
x1r5 = in2(:,5);
x2r1 = in4(:,1);
x2r2 = in4(:,2);
x2r3 = in4(:,3);
x2r4 = in4(:,4);
x2r5 = in4(:,5);
x1ry1r1 = in6(:,1);
x1ry1r2 = in6(:,2);
x1ry1r3 = in6(:,3);
x1ry1r4 = in6(:,4);
x1ry1r5 = in6(:,5);
y1r1 = in3(:,1);
y1r2 = in3(:,2);
y1r3 = in3(:,3);
y1r4 = in3(:,4);
y1r5 = in3(:,5);
y2r1 = in5(:,1);
y2r2 = in5(:,2);
y2r3 = in5(:,3);
y2r4 = in5(:,4);
y2r5 = in5(:,5);
t2 = va1-va2;
t3 = va1-va3;
t4 = va1-va4;
t5 = va1-va5;
t6 = va1-va6;
t7 = t2.*x1r1;
t8 = t3.*x1r2;
t9 = t4.*x1r3;
t10 = t5.*x1r4;
t11 = t6.*x1r5;
t12 = t7+t8+t9+t10+t11;
t13 = t2.*x2r1;
t14 = t3.*x2r2;
t15 = t4.*x2r3;
t16 = t5.*x2r4;
t17 = t6.*x2r5;
t18 = t13+t14+t15+t16+t17;
t19 = t2.*x1ry1r1;
t20 = t3.*x1ry1r2;
t21 = t4.*x1ry1r3;
t22 = t5.*x1ry1r4;
t23 = t6.*x1ry1r5;
t24 = t19+t20+t21+t22+t23;
t25 = t2.*y1r1;
t26 = t3.*y1r2;
t27 = t4.*y1r3;
t28 = t5.*y1r4;
t29 = t6.*y1r5;
t30 = t25+t26+t27+t28+t29;
t31 = t2.*y2r1;
t32 = t3.*y2r2;
t33 = t4.*y2r3;
t34 = t5.*y2r4;
t35 = t6.*y2r5;
t36 = t31+t32+t33+t34+t35;
dux = -A11.*t12-A13.*t18-A15.*t24-A12.*t30-A14.*t36;
if nargout > 1
    duy = -A21.*t12-A23.*t18-A25.*t24-A22.*t30-A24.*t36;
end
if nargout > 2
    duxx = A31.*t12.*-2.0-A33.*t18.*2.0-A35.*t24.*2.0-A32.*t30.*2.0-A34.*t36.*2.0;
end
if nargout > 3
    duyy = A41.*t12.*-2.0-A43.*t18.*2.0-A45.*t24.*2.0-A42.*t30.*2.0-A44.*t36.*2.0;
end
if nargout > 4
    duxy = -A51.*t12-A53.*t18-A55.*t24-A52.*t30-A54.*t36;
end
